### ISSUE TITLE
Few problems with intercept

### ISSUE THREAD

**Issue by ugintl** [AtenDesignGroup/intercept-pantheon-upstream#34]
I installed it on pantheon. It installed smoothly. However, I see some bugs. I am logged in as admin.

1. /user does not redirect to user profile. "You are not authorised to access this page".

2. /account/settings gives "You are not authorised to access this page"

Errors from the log are attached

[intercept-errors.txt](https://github.com/AtenDesignGroup/intercept-pantheon-upstream/files/6650431/intercept-errors.txt)

**Comment by ugintl** [comment]
Moreover, design needs some improvements.

**Comment by attheshow** [comment]
Since this issue is a bit outdated and hasn't received any further discussion (and a LOT has changed in the last 2 years), I'll go ahead and close this issue. Feel free to reopen with updated information and logs if necessary.
